In [1]:
import pandas as pd

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
# Load training data
history = pd.read_csv('https://raw.githubusercontent.com/samsung-ai-course/8th-9th-edition/main/Supervised%20learning%20Hackathon%20-%20Edition%209/data/history.csv')
history.head(2)
history.shape

,id,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,37980,32.0,male,Associate,96865.0,10,MORTGAGE,7500.0,EDUCATION,6.04,0.08,10.0,601,No,0
1,9912,24.0,male,Associate,56838.0,6,RENT,9000.0,EDUCATION,11.49,0.16,4.0,647,Yes,0

(38250, 15)

In [3]:
history.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38250 entries, 0 to 38249
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              38250 non-null  int64
 1   person_age                      38250 non-null  float64
 2   person_gender                   38250 non-null  object
 3   person_education                38250 non-null  object
 4   person_income                   38250 non-null  float64
 5   person_emp_exp                  38250 non-null  int64
 6   person_home_ownership           38250 non-null  object
 7   loan_amnt                       38250 non-null  float64
 8   loan_intent                     38250 non-null  object
 9   loan_int_rate                   38250 non-null  float64
 10  loan_percent_income             38250 non-null  float64
 11  cb_person_cred_hist_length      38250 non-null  float64
 12  credit_score                    38250 non-null  int64
 13  previous_loan_defaults_on_file  38250 non-null  object
 14  loan_status                     38250 non-null  int64
dtypes: float64(6), int64(4), object(5)
memory usage: 4.4+ MB

In [6]:
history['person_gender'].value_counts()

person_gender
male      21103
female    17147
Name: count, dtype: int64

In [11]:
history['person_gender'] = history['person_gender'].replace({'male': 0, 'female': 1})

/tmp/ipython-input-3418623177.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  history['person_gender'] = history['person_gender'].replace({'male': 0, 'female': 1})

In [7]:
history['person_education'].value_counts()

person_education
Bachelor       11382
High School    10220
Associate      10194
Master          5913
Doctorate        541
Name: count, dtype: int64

In [13]:
history['person_education'] = history['person_education'].replace({'Bachelor': 0, 'High School': 1, 'Associate': 2, 'Master': 3, 'Doctorate': 4})

/tmp/ipython-input-720022216.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  history['person_education'] = history['person_education'].replace({'Bachelor': 0, 'High School': 1, 'Associate': 2, 'Master': 3, 'Doctorate': 4})

In [8]:
history['loan_intent'].value_counts()

loan_intent
EDUCATION            7780
MEDICAL              7257
VENTURE              6677
PERSONAL             6407
DEBTCONSOLIDATION    6052
HOMEIMPROVEMENT      4077
Name: count, dtype: int64

In [14]:
history['loan_intent'] = history['loan_intent'].replace({'EDUCATION': 0, 'MEDICAL': 1, 'VENTURE': 2, 'PERSONAL': 3, 'DEBTCONSOLIDATION': 4, 'HOMEIMPROVEMENT': 5})

/tmp/ipython-input-3884243055.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  history['loan_intent'] = history['loan_intent'].replace({'EDUCATION': 0, 'MEDICAL': 1, 'VENTURE': 2, 'PERSONAL': 3, 'DEBTCONSOLIDATION': 4, 'HOMEIMPROVEMENT': 5})

In [9]:
history['previous_loan_defaults_on_file'].value_counts()

previous_loan_defaults_on_file
Yes    19425
No     18825
Name: count, dtype: int64

In [15]:
history['previous_loan_defaults_on_file'] = history['previous_loan_defaults_on_file'].replace({'Yes': 0, 'No': 1})

/tmp/ipython-input-1443841575.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  history['previous_loan_defaults_on_file'] = history['previous_loan_defaults_on_file'].replace({'Yes': 0, 'No': 1})

In [10]:
history['loan_status'].value_counts()

loan_status
0    29761
1     8489
Name: count, dtype: int64

In [18]:
history['person_home_ownership'].value_counts()

person_home_ownership
RENT        19929
MORTGAGE    15742
OWN          2477
OTHER         102
Name: count, dtype: int64

In [19]:
history['person_home_ownership'] = history['person_home_ownership'].replace({'RENT': 0, 'MORTGAGE': 1, 'OWN': 2, 'OTHER': 3})

/tmp/ipython-input-1785946384.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  history['person_home_ownership'] = history['person_home_ownership'].replace({'RENT': 0, 'MORTGAGE': 1, 'OWN': 2, 'OTHER': 3})

In [20]:
y = history['loan_status']
X = history.drop(columns=['loan_status','id'])

In [21]:
X.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file
0,32.0,0,2,96865.0,10,1,7500.0,0,6.04,0.08,10.0,601,1
1,24.0,0,2,56838.0,6,0,9000.0,0,11.49,0.16,4.0,647,0
2,22.0,1,3,37298.0,0,0,5000.0,1,14.88,0.13,4.0,711,1
3,23.0,1,0,39944.0,1,2,5000.0,2,13.99,0.13,3.0,597,0
4,42.0,0,1,67974.0,20,1,10000.0,5,15.41,0.15,11.0,586,1

In [22]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
# Load test data
test = pd.read_csv('https://raw.githubusercontent.com/samsung-ai-course/8th-9th-edition/main/Supervised%20learning%20Hackathon%20-%20Edition%209/data/test.csv')
test.head(2)
test.shape

,id,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file
0,43299,22.0,female,Bachelor,56179.0,0,RENT,5000.0,EDUCATION,11.01,0.09,3.0,571,No
1,15156,23.0,male,Bachelor,151219.0,2,MORTGAGE,35000.0,EDUCATION,8.90,0.23,4.0,561,Yes

(6750, 14)

In [ ]:
# Load sample submission
sample_submission = pd.read_csv('https://raw.githubusercontent.com/samsung-ai-course/8th-9th-edition/main/Supervised%20learning%20Hackathon%20-%20Edition%209/data/sample_submission.csv')
sample_submission.head(2)
sample_submission.shape